title: Eve-bot
description: "---EVE: A Project for a Top-Tier IRC Bot--- Eve was originally designed on an entirely different framework and language and has grown through the years. Now Eve is on Ruby and the Cinch IRC Framework. If you need help you can join #Eve on irc.sinsira.net"
google_analytics: 
show_downloads: true
theme: jekyll-theme-midnight

gems:
  - jekyll-mentions
